### ISSUE TITLE
Warning: Some domains in namelist.tailor have the same WRF file

### ISSUE THREAD

**Issue by ksunilk** [anikfal/wrftailor#8]
Hi Amir,

There was a warning, when I tried to execute ./wrftailor.sh for a single domain, 

_Warning: Some domains in namelist.tailor have the same WRF file
Exiting .._

When I tried the second domain with a dummy file, with path, it showed another warning,

./wrftailor.sh: line 318: 508695 Segmentation fault      (core dumped) ncl -Qn bounding.ncl

I am unable to identify the issue.

Regards
Sunil

**Comment by anikfal** [comment]
Thank you for reporting. The issue is resolved now.
